Bump version, oops!
mbullington/node_preamble.dart pull request #23
Opened 2021-01-20 12:18 UTC by Mstrodl

Forgot to bump the version in my last PR(!)
This does that and adds it to the changelog as well as the previous nullsafety version.

2021-01-20 12:19 UTC, Mstrodl commented
Adding @jathak here as well, should I keep the `-nullsafety` tag at the end of future versions?

2021-01-22 23:30 UTC, Awjin commented
@Mstrodl We decided to [revert the null-safe changes](https://github.com/mbullington/node_preamble.dart/pull/24) for now. If you rebase this PR on master and bump the version to `1.4.13` we should be good to go.

2021-01-23 16:42 UTC, Mstrodl commented
@Awjin All done, just need an approving review :p

2021-01-23 17:06 UTC, Awjin requested changes

2021-01-23 17:06 UTC, Awjin commented on CHANGELOG.md
> +# 1.4.13-nullsafety
You can remove this entry and instead mark the Electron entry as 1.4.13

2021-01-23 17:54 UTC, Mstrodl commented
going to cc @mbullington because I believe we still need you to publish to pub.dev :)

2021-01-23 18:06 UTC, Awjin approved these changes

2021-01-23 18:06 UTC, merged

2021-01-25 03:31 UTC, mbullington commented
@Mstrodl Taken care of, published. Thanks for helping maintain all, cheers!